# Generated by Django 2.2.5 on 2019-11-30 14:24

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191130_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.ImageField(upload_to=products.models.path_and_rename),
        ),
    ]
