# Generated by Django 2.2.5 on 2019-12-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20191207_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='payment',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
