# Generated by Django 2.2.5 on 2019-12-10 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customers_barista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='barista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
